/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parsed_vision.proto */

#ifndef PROTOBUF_C_parsed_5fvision_2eproto__INCLUDED
#define PROTOBUF_C_parsed_5fvision_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Vector2 Vector2;
typedef struct _Robot Robot;
typedef struct _ParsedFrame ParsedFrame;


/* --- enums --- */


/* --- messages --- */

struct  _Vector2
{
  ProtobufCMessage base;
  float x;
  float y;
};
#define VECTOR2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&vector2__descriptor) \
    , 0, 0 }


struct  _Robot
{
  ProtobufCMessage base;
  uint32_t robot_id;
  Vector2 *pos;
  float orientation;
  Vector2 *vel;
};
#define ROBOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot__descriptor) \
    , 0, NULL, 0, NULL }


struct  _ParsedFrame
{
  ProtobufCMessage base;
  size_t n_robots;
  Robot **robots;
  Vector2 *ball;
};
#define PARSED_FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parsed_frame__descriptor) \
    , 0,NULL, NULL }


/* Vector2 methods */
void   vector2__init
                     (Vector2         *message);
size_t vector2__get_packed_size
                     (const Vector2   *message);
size_t vector2__pack
                     (const Vector2   *message,
                      uint8_t             *out);
size_t vector2__pack_to_buffer
                     (const Vector2   *message,
                      ProtobufCBuffer     *buffer);
Vector2 *
       vector2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   vector2__free_unpacked
                     (Vector2 *message,
                      ProtobufCAllocator *allocator);
/* Robot methods */
void   robot__init
                     (Robot         *message);
size_t robot__get_packed_size
                     (const Robot   *message);
size_t robot__pack
                     (const Robot   *message,
                      uint8_t             *out);
size_t robot__pack_to_buffer
                     (const Robot   *message,
                      ProtobufCBuffer     *buffer);
Robot *
       robot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robot__free_unpacked
                     (Robot *message,
                      ProtobufCAllocator *allocator);
/* ParsedFrame methods */
void   parsed_frame__init
                     (ParsedFrame         *message);
size_t parsed_frame__get_packed_size
                     (const ParsedFrame   *message);
size_t parsed_frame__pack
                     (const ParsedFrame   *message,
                      uint8_t             *out);
size_t parsed_frame__pack_to_buffer
                     (const ParsedFrame   *message,
                      ProtobufCBuffer     *buffer);
ParsedFrame *
       parsed_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parsed_frame__free_unpacked
                     (ParsedFrame *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Vector2_Closure)
                 (const Vector2 *message,
                  void *closure_data);
typedef void (*Robot_Closure)
                 (const Robot *message,
                  void *closure_data);
typedef void (*ParsedFrame_Closure)
                 (const ParsedFrame *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor vector2__descriptor;
extern const ProtobufCMessageDescriptor robot__descriptor;
extern const ProtobufCMessageDescriptor parsed_frame__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_parsed_5fvision_2eproto__INCLUDED */
