/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parsed_vision.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "parsed_vision.pb-c.h"
void   vector2__init
                     (Vector2         *message)
{
  static const Vector2 init_value = VECTOR2__INIT;
  *message = init_value;
}
size_t vector2__get_packed_size
                     (const Vector2 *message)
{
  assert(message->base.descriptor == &vector2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vector2__pack
                     (const Vector2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vector2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vector2__pack_to_buffer
                     (const Vector2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vector2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vector2 *
       vector2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vector2 *)
     protobuf_c_message_unpack (&vector2__descriptor,
                                allocator, len, data);
}
void   vector2__free_unpacked
                     (Vector2 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vector2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   robot__init
                     (Robot         *message)
{
  static const Robot init_value = ROBOT__INIT;
  *message = init_value;
}
size_t robot__get_packed_size
                     (const Robot *message)
{
  assert(message->base.descriptor == &robot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robot__pack
                     (const Robot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robot__pack_to_buffer
                     (const Robot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Robot *
       robot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Robot *)
     protobuf_c_message_unpack (&robot__descriptor,
                                allocator, len, data);
}
void   robot__free_unpacked
                     (Robot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &robot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parsed_frame__init
                     (ParsedFrame         *message)
{
  static const ParsedFrame init_value = PARSED_FRAME__INIT;
  *message = init_value;
}
size_t parsed_frame__get_packed_size
                     (const ParsedFrame *message)
{
  assert(message->base.descriptor == &parsed_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parsed_frame__pack
                     (const ParsedFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parsed_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parsed_frame__pack_to_buffer
                     (const ParsedFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parsed_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParsedFrame *
       parsed_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParsedFrame *)
     protobuf_c_message_unpack (&parsed_frame__descriptor,
                                allocator, len, data);
}
void   parsed_frame__free_unpacked
                     (ParsedFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parsed_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vector2__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vector2__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange vector2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vector2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Vector2",
  "Vector2",
  "Vector2",
  "",
  sizeof(Vector2),
  2,
  vector2__field_descriptors,
  vector2__field_indices_by_name,
  1,  vector2__number_ranges,
  (ProtobufCMessageInit) vector2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor robot__field_descriptors[4] =
{
  {
    "robot_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Robot, robot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot, pos),
    &vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orientation",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Robot, orientation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vel",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot, vel),
    &vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robot__field_indices_by_name[] = {
  2,   /* field[2] = orientation */
  1,   /* field[1] = pos */
  0,   /* field[0] = robot_id */
  3,   /* field[3] = vel */
};
static const ProtobufCIntRange robot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor robot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Robot",
  "Robot",
  "Robot",
  "",
  sizeof(Robot),
  4,
  robot__field_descriptors,
  robot__field_indices_by_name,
  1,  robot__number_ranges,
  (ProtobufCMessageInit) robot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parsed_frame__field_descriptors[2] =
{
  {
    "robots",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ParsedFrame, n_robots),
    offsetof(ParsedFrame, robots),
    &robot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ball",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ParsedFrame, ball),
    &vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parsed_frame__field_indices_by_name[] = {
  1,   /* field[1] = ball */
  0,   /* field[0] = robots */
};
static const ProtobufCIntRange parsed_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parsed_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParsedFrame",
  "ParsedFrame",
  "ParsedFrame",
  "",
  sizeof(ParsedFrame),
  2,
  parsed_frame__field_descriptors,
  parsed_frame__field_indices_by_name,
  1,  parsed_frame__number_ranges,
  (ProtobufCMessageInit) parsed_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
