/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: robot_action.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "robot_action.pb-c.h"
void   action__command__init
                     (Action__Command         *message)
{
  static const Action__Command init_value = ACTION__COMMAND__INIT;
  *message = init_value;
}
size_t action__command__get_packed_size
                     (const Action__Command *message)
{
  assert(message->base.descriptor == &action__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action__command__pack
                     (const Action__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action__command__pack_to_buffer
                     (const Action__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Action__Command *
       action__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Action__Command *)
     protobuf_c_message_unpack (&action__command__descriptor,
                                allocator, len, data);
}
void   action__command__free_unpacked
                     (Action__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action__vector3_d__init
                     (Action__Vector3D         *message)
{
  static const Action__Vector3D init_value = ACTION__VECTOR3_D__INIT;
  *message = init_value;
}
size_t action__vector3_d__get_packed_size
                     (const Action__Vector3D *message)
{
  assert(message->base.descriptor == &action__vector3_d__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action__vector3_d__pack
                     (const Action__Vector3D *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action__vector3_d__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action__vector3_d__pack_to_buffer
                     (const Action__Vector3D *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action__vector3_d__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Action__Vector3D *
       action__vector3_d__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Action__Vector3D *)
     protobuf_c_message_unpack (&action__vector3_d__descriptor,
                                allocator, len, data);
}
void   action__vector3_d__free_unpacked
                     (Action__Vector3D *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action__vector3_d__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action__vector2_d__init
                     (Action__Vector2D         *message)
{
  static const Action__Vector2D init_value = ACTION__VECTOR2_D__INIT;
  *message = init_value;
}
size_t action__vector2_d__get_packed_size
                     (const Action__Vector2D *message)
{
  assert(message->base.descriptor == &action__vector2_d__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action__vector2_d__pack
                     (const Action__Vector2D *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action__vector2_d__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action__vector2_d__pack_to_buffer
                     (const Action__Vector2D *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action__vector2_d__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Action__Vector2D *
       action__vector2_d__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Action__Vector2D *)
     protobuf_c_message_unpack (&action__vector2_d__descriptor,
                                allocator, len, data);
}
void   action__vector2_d__free_unpacked
                     (Action__Vector2D *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action__vector2_d__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor action__command__field_descriptors[7] =
{
  {
    "command_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Action__Command, command_id),
    &action__action_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "robot_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Action__Command, robot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kick_speed",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Action__Command, kick_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Action__Command, pos),
    &action__vector3_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dest",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Action__Command, dest),
    &action__vector3_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Action__Command, direction),
    &action__vector2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angular_vel",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Action__Command, angular_vel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action__command__field_indices_by_name[] = {
  6,   /* field[6] = angular_vel */
  0,   /* field[0] = command_id */
  4,   /* field[4] = dest */
  5,   /* field[5] = direction */
  2,   /* field[2] = kick_speed */
  3,   /* field[3] = pos */
  1,   /* field[1] = robot_id */
};
static const ProtobufCIntRange action__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor action__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "action.Command",
  "Command",
  "Action__Command",
  "action",
  sizeof(Action__Command),
  7,
  action__command__field_descriptors,
  action__command__field_indices_by_name,
  1,  action__command__number_ranges,
  (ProtobufCMessageInit) action__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action__vector3_d__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Action__Vector3D, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Action__Vector3D, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Action__Vector3D, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action__vector3_d__field_indices_by_name[] = {
  2,   /* field[2] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange action__vector3_d__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor action__vector3_d__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "action.Vector3D",
  "Vector3D",
  "Action__Vector3D",
  "action",
  sizeof(Action__Vector3D),
  3,
  action__vector3_d__field_descriptors,
  action__vector3_d__field_indices_by_name,
  1,  action__vector3_d__number_ranges,
  (ProtobufCMessageInit) action__vector3_d__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action__vector2_d__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Action__Vector2D, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Action__Vector2D, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action__vector2_d__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange action__vector2_d__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action__vector2_d__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "action.Vector2D",
  "Vector2D",
  "Action__Vector2D",
  "action",
  sizeof(Action__Vector2D),
  2,
  action__vector2_d__field_descriptors,
  action__vector2_d__field_indices_by_name,
  1,  action__vector2_d__number_ranges,
  (ProtobufCMessageInit) action__vector2_d__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue action__action_type__enum_values_by_number[6] =
{
  { "STOP_ACTION", "ACTION__ACTION_TYPE__STOP_ACTION", 0 },
  { "KICK_ACTION", "ACTION__ACTION_TYPE__KICK_ACTION", 1 },
  { "MOVE_ACTION", "ACTION__ACTION_TYPE__MOVE_ACTION", 2 },
  { "INIT_ACTION", "ACTION__ACTION_TYPE__INIT_ACTION", 3 },
  { "SET_NAVIGATION_DIRECTION_ACTION", "ACTION__ACTION_TYPE__SET_NAVIGATION_DIRECTION_ACTION", 4 },
  { "ROTATE_ACTION", "ACTION__ACTION_TYPE__ROTATE_ACTION", 5 },
};
static const ProtobufCIntRange action__action_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex action__action_type__enum_values_by_name[6] =
{
  { "INIT_ACTION", 3 },
  { "KICK_ACTION", 1 },
  { "MOVE_ACTION", 2 },
  { "ROTATE_ACTION", 5 },
  { "SET_NAVIGATION_DIRECTION_ACTION", 4 },
  { "STOP_ACTION", 0 },
};
const ProtobufCEnumDescriptor action__action_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "action.ActionType",
  "ActionType",
  "Action__ActionType",
  "action",
  6,
  action__action_type__enum_values_by_number,
  6,
  action__action_type__enum_values_by_name,
  1,
  action__action_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
