/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "ssl_wrapper_tracked.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TrackerWrapperPacket, TrackerWrapperPacket, AUTO)



